In [3]:
# Análisis del Conjunto de Datos Iris

# Importar las librerías necesarias
from sklearn.datasets import fetch_openml  # type: ignore
import pandas as pd  # type: ignore

# Descargar la base de datos "Iris" desde OpenML, con parser='auto' para evitar la advertencia
dataset = fetch_openml(name='iris', version=1, as_frame=True, parser='auto')

# Crear un DataFrame a partir de los datos descargados
df = dataset.frame

# Mostrar las primeras filas del DataFrame
print("Primeras filas del dataset 'Iris':")
display(df.head())  # Para mostrar en formato de tabla en Jupyter

# Descripción general de las variables
print("\nDescripción de las variables del dataset:")
df.info()  # Proporciona información sobre los tipos de variables y valores faltantes

# Identificación del tipo de variable (numérica discreta, continua, categórica)
print("\nIdentificación de los tipos de variables:")
for column in df.columns:
    dtype = df[column].dtype
    if pd.api.types.is_numeric_dtype(dtype):
        if pd.api.types.is_integer_dtype(dtype):
            var_type = "Numérica Discreta"
        else:
            var_type = "Numérica Continua"
    else:
        var_type = "Categórica"
    
    print(f"Variable '{column}': {var_type}")

Primeras filas del dataset 'Iris':

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

Descripción de las variables del dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sepallength  150 non-null    float64
 1   sepalwidth   150 non-null    float64
 2   petallength  150 non-null    float64
 3   petalwidth   150 non-null    float64
 4   class        150 non-null    category
dtypes: category(1), float64(4)
memory usage: 5.1 KB

Identificación de los tipos de variables:
Variable 'sepallength': Numérica Continua
Variable 'sepalwidth': Numérica Continua
Variable 'petallength': Numérica Continua
Variable 'petalwidth': Numérica Continua
Variable 'class': Categórica